### PR TITLE
Release 2.0.1-dexda 

### PR DESCRIPTION
**Pull request by tjshippey**
DEV-82546][DEV-85126] Updates for JDK 11/Scala 2.12/Spark 2.4

### CODE REVIEW

**Comment by jamesrgrinter** [comment]
I'll ask Matt to look over this, as I wrote the code and you created the PR!

**Comment by tjshippey** [comment]
https://github.com/TESMLTD/spark-metrics/pull/3 will need to be completed first

**Comment by jamesrgrinter** [comment]
(update: TJS pointed out this is just a "release" PR.)

**Review by w33v1l — APPROVED** [review]
LGTM

**Pull request merged**
